# Web Scraping for Indeed.com & Predicting Salaries

In this project, we will practice two major skills: collecting data by scraping a website and then building a binary classifier.

We are going to collect salary information on data science jobs in a variety of markets. Then using the location, title, and summary of the job we will attempt to predict the salary of the job. For job posting sites, this would be extraordinarily useful. While most listings DO NOT come with salary information (as you will see in this exercise), being to able extrapolate or predict the expected salaries from other listings can help guide negotiations.

Normally, we could use regression for this task; however, we will convert this problem into classification and use a random forest classifier, as well as another classifier of your choice; either logistic regression, SVM, or KNN. 

- **Question**: Why would we want this to be a classification problem?
- **Answer**: While more precision may be better, there is a fair amount of natural variance in job salaries - predicting a range be may be useful.

Therefore, the first part of the assignment will be focused on scraping Indeed.com. In the second, we'll focus on using listings with salary information to build a model and predict additional salaries.

### Scraping job listings from Indeed.com

We will be scraping job listings from Indeed.com using BeautifulSoup. Luckily, Indeed.com is a simple text page where we can easily find relevant entries.

First, look at the source of an Indeed.com page: (http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start=10")

Notice, each job listing is underneath a `div` tag with a class name of `result`. We can use BeautifulSoup to extract those.

#### Set up a request (using requests) to the URL below. Use BeautifulSoup to parse the page and extract all results (HINT: Look for div tags with class name result)
The URL here has many query parameters
- q for the job search
- This is followed by "+20,000" to return results with salaries (or expected salaries >$20,000)
- l for a location
- start for what result number to start on

In [73]:
URL = "http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start=10"
# base_url = 'http://www.indeed.com/jobs?q=data+scientist&jt=fulltime&sort=' 

# base_url = 'https://www.indeed.com/jobs?q=data+scientist&l='

In [74]:
import requests
import bs4
from bs4 import BeautifulSoup

In [75]:
## YOUR CODE HERE
r = requests.get(URL)

soup = BeautifulSoup(r.text,"html.parser")

print(soup.find('div',attrs= {"class":"row result"})).text
#soup.body

Senior Data Scientist



    NIT Finance

 - New York, NY


Data Scientist Responsibilities:. Working in Enterprise Data Management organization, the Senior Data Scientist will work with data teams to evolve machine...



 Easily apply


Sponsored - 3 days ago   -  save jobwindow['sj_result_293a1db47cfb7b74'] = {"showSource": false, "source": "Indeed", "loggedIn": false, "showMyJobsLinks": true,"undoAction": "unsave","relativeJobAge": "3 days ago","jobKey": "293a1db47cfb7b74", "myIndeedAvailable": true, "tellAFriendEnabled": false, "showMoreActionsLink": false, "resultNumber": 10, "jobStateChangedToSaved": false, "searchState": "q=data scientist $20,000&amp;l=New+York&amp;start=10", "basicPermaLink": "http://www.indeed.com", "saveJobFailed": false, "removeJobFailed": false, "requestPending": false, "notesEnabled": false, "currentPage" : "serp", "sponsored" : true,"showSponsor" : true,"reportJobButtonEnabled": false, "showMyJobsHired": false, "showSaveForSponsored": true, "showJobAge": true};

In [76]:
for entry in soup.find_all(name='div', attrs={'class':'row result'}):
    try:
        print entry.text
    except:
        print "ZERO"

Senior Data Scientist



    NIT Finance

 - New York, NY


Data Scientist Responsibilities:. Working in Enterprise Data Management organization, the Senior Data Scientist will work with data teams to evolve machine...



 Easily apply


Sponsored - 3 days ago   -  save jobwindow['sj_result_293a1db47cfb7b74'] = {"showSource": false, "source": "Indeed", "loggedIn": false, "showMyJobsLinks": true,"undoAction": "unsave","relativeJobAge": "3 days ago","jobKey": "293a1db47cfb7b74", "myIndeedAvailable": true, "tellAFriendEnabled": false, "showMoreActionsLink": false, "resultNumber": 10, "jobStateChangedToSaved": false, "searchState": "q=data scientist $20,000&amp;l=New+York&amp;start=10", "basicPermaLink": "http://www.indeed.com", "saveJobFailed": false, "removeJobFailed": false, "requestPending": false, "notesEnabled": false, "currentPage" : "serp", "sponsored" : true,"showSponsor" : true,"reportJobButtonEnabled": false, "showMyJobsHired": false, "showSaveForSponsored": true, "showJobAge": true};







People Analytics & Research Data Scientist




        BlackRock

 -
173 reviews
 - New York, NY 10001


We are looking for a data scientist with advanced skills in mathematics, technology and data mining to help build algorithms that leverage large quantities of...



Sponsored - save jobwindow['sj_result_e4ae3d5a0b7c9106'] = {"showSource": false, "source": "BlackRock", "loggedIn": false, "showMyJobsLinks": true,"undoAction": "unsave","jobKey": "e4ae3d5a0b7c9106", "myIndeedAvailable": true, "tellAFriendEnabled": false, "showMoreActionsLink": false, "resultNumber": 11, "jobStateChangedToSaved": false, "searchState": "q=data scientist $20,000&amp;l=New+York&amp;start=10", "basicPermaLink": "http://www.indeed.com", "saveJobFailed": false, "removeJobFailed": false, "requestPending": false, "notesEnabled": false, "currentPage" : "serp", "sponsored" : true,"showSponsor" : true,"reportJobButtonEnabled": false, "showMyJobsHired": false, "showSaveForSponsored": true, "showJobAge": true};







Applied Machine Learning Scientist/Engineer - Relevance & Di...




        Bloomberg

 -
332 reviews
 - New York, NY


Information and data move the financial markets. This data would be unmanageable without our help. Bloomberg ingests more than 70,000 different news feeds,...



Sponsored - save jobwindow['sj_result_e03998bf5146cf67'] = {"showSource": false, "source": "Bloomberg", "loggedIn": false, "showMyJobsLinks": true,"undoAction": "unsave","jobKey": "e03998bf5146cf67", "myIndeedAvailable": true, "tellAFriendEnabled": false, "showMoreActionsLink": false, "resultNumber": 13, "jobStateChangedToSaved": false, "searchState": "q=data scientist $20,000&amp;l=New+York&amp;start=10", "basicPermaLink": "http://www.indeed.com", "saveJobFailed": false, "removeJobFailed": false, "requestPending": false, "notesEnabled": false, "currentPage" : "serp", "sponsored" : true,"showSponsor" : true,"reportJobButtonEnabled": false, "showMyJobsHired": false, "showSaveForSponsored": true, "showJobAge": true};

In [77]:
for entry in soup.find_all(name='span', attrs={'class':'location'}):
    print entry.text

New York, NY
New York, NY 10001
New York, NY
New York, NY
New York, NY
New York, NY
New York, NY 10011 (Chelsea area)
New York, NY
New York, NY
New York, NY
New York, NY 10032 (Washington Heights area)
New York, NY
New York, NY 10018 (Clinton area)
New York, NY
New York, NY 10154

In [78]:
for entry in soup.find_all(name='a', attrs={'class':'jobtitle turnstileLink'}):
    print entry.text

Senior Data Scientist
People Analytics & Research Data Scientist
Quantitative Analyst III - Model Risk Execution
Applied Machine Learning Scientist/Engineer - Relevance & Di...
Data Scientist - Big Data & Analytics

In [79]:
for entry in soup.find_all(name='td', attrs={'id':'resultsCol'}):
    print entry.renderContents()

<div class="messageContainer">
<script type="text/javascript">
function setJaPromoCookie() {
var expires = new Date();
expires.setTime(expires.getTime() + (5 * 365 * 24 * 60 * 60 * 1000));
setCookie("showJaPromo", "1", expires);
}
function setRefineByCookie(refineByTypes) {
var expires = new Date();
expires.setTime(expires.getTime() + (10 * 1000));
for (var i = 0; i < refineByTypes.length; i++) {
setCookie(refineByTypes[i], "1", expires);
}
}
</script>
</div>
<style type="text/css">
#increased_radius_result {
font-size: 16px;
font-style: italic;
}
#original_radius_result{
font-size: 13px;
font-style: italic;
}
</style>
<div class="resultsTop"><div id="searchCount">Jobs 11 to 20 of 2,225</div>
<div data-tn-section="primePromo" id="primePromo">
<span class="new">New!</span> <a href="/promo/prime" onclick="this.href = appendParamsOnce( this.href, '?from=serptop&amp;subfrom=primeprmtop&amp;trk.origin=jobsearch&amp;trk.variant=primeprmtop&amp;trk.tk=1bdc1fgnvbi63eeq&amp;vertical=TECH&amp;x_isid=serptop&amp;x_ikw=data+scientist+%2420%2C000&amp;x_sid=serptop&amp;x_kw=data+scientist+%2420%2C000')">Join Indeed Prime</a> - Get offers from great tech companies</div></div>
<script type="text/javascript">
window['sjl'] = "VGEdO9g73";
</script>
<style type="text/css">
.VGEdO9g73 { margin: 0 0 6px 0; padding: 0; _zoom:100%; border: 0; background-color: #fff; }
.VGEdO9g73 .jobtitle { white-space: nowrap; float:@LINE_START@; _float: none; }
.VGEdO9g73 .sdn { color: #CD29C0; }
.qo982bSF .brdr { margin-top: 12px; }
.xNXdusgRO .brdr { margin-bottom: 12px; }
@media only screen and (min-height:780px) {
.qo982bSF { margin-bottom: 9px; }
.xNXdusgRO .brdr,
.GocLza7ioh,
.qo982bSF .brdr { margin-bottom: 9px; margin-top: 9px; }
}
</style>
<style type="text/css">
.result-tab:empty {margin-top: 0;}
.qo982bSF {
margin-bottom: 0;
}
@media only screen and (min-height:780px) {
.qo982bSF {
margin-bottom: 0;
}
}
</style>
<div></div>
<a id="jobPostingsAnchor" tabindex="-1"></a>
<div class="VGEdO9g73 qo982bSF">
<div class="row result" data-jk="293a1db47cfb7b74" id="pj_293a1db47cfb7b74">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/pagead/clk?mo=r&amp;ad=-6NYlbfkN0DiY4KvqzxM3XGxyY5yPthzVYWdnNruR-f465HtevyEM2zA1XgC-Su17TCwGTy8XYKqZvT_tZtWtoOK_JTiESRvR4Dg5adlDIj_Y6ir6ecXOXJ9a58XldYVpgVjpeyoy4cgVBwu4p7KKQ8XveF1EYHIE-NORFI8uLN4DXM49C8BTE5FE77o4wa1uMp5MIsibrZHRle6rE0lgwSp6U7YCLm1TvTJPR6HJZLqSr4Q1JJW8ByucpRxgiXyFnzyCtuTreui-CRjR5xqIbRgPPvOqkHMu8abyFAU3fJU8KMl4Mn6qmtBPnu8E3Aq3hBgCAZnEkikTI2xMWXWTy3jDdawodTOyvz52NScQNTHOL2Fcwhrz-bpxuV3hov2zpxkLygNJzsJg2OQbEVSStadWcgmNNCsOZubqCp9BOI4P9CAQo865RC2yYu6UJ92eVkLOg0leJA=&amp;p=1&amp;sk=&amp;fvj=1" id="sja1" onclick="setRefineByCookie(['salest']); sjoc('sja1',0); convCtr('SJ', pingUrlsForGA)" onmousedown="sjomd('sja1'); clk('sja1');" rel="nofollow" target="_blank" title="Senior Data Scientist">Senior <b>Data</b> <b>Scientist</b></a>
<br>
<div class="sjcl">
<span class="company">
    NIT Finance</span>

 - <span class="location">New York, NY</span>
</div>
<table border="0" cellpadding="0" cellspacing="0"><tr><td class="snip">
<span class="summary"><b>Data</b> <b>Scientist</b> Responsibilities:. Working in Enterprise <b>Data</b> Management organization, the Senior <b>Data</b> <b>Scientist</b> will work with <b>data</b> teams to evolve machine...</span>
</td></tr></table>
<div class="sjCapt">
<div class="iaP">
<span class="iaLabel"> Easily apply</span>
</div>
<div class="result-link-bar-container">
<div class="result-link-bar"><span class=" jasx_serpsjlabel_poststGray ">Sponsored</span> - <span class="date">3 days ago</span> <span class="tt_set" id="tt_set_10">  -  <span class="savelink2" id="savelink2_293a1db47cfb7b74"><a class="sl resultLink save-job-link" href="#" id="sj_293a1db47cfb7b74" onclick="changeJobState('293a1db47cfb7b74', 'save', 'linkbar', true);return false;" title="Save this job to my.indeed">save job</a></span></span><div class="edit_note_content" id="editsaved2_293a1db47cfb7b74" style="display:none;"></div><script>window['sj_result_293a1db47cfb7b74'] = {"showSource": false, "source": "Indeed", "loggedIn": false, "showMyJobsLinks": true,"undoAction": "unsave","relativeJobAge": "3 days ago","jobKey": "293a1db47cfb7b74", "myIndeedAvailable": true, "tellAFriendEnabled": false, "showMoreActionsLink": false, "resultNumber": 10, "jobStateChangedToSaved": false, "searchState": "q=data scientist $20,000&amp;l=New+York&amp;start=10", "basicPermaLink": "http://www.indeed.com", "saveJobFailed": false, "removeJobFailed": false, "requestPending": false, "notesEnabled": false, "currentPage" : "serp", "sponsored" : true,"showSponsor" : true,"reportJobButtonEnabled": false, "showMyJobsHired": false, "showSaveForSponsored": true, "showJobAge": true};</script></div></div>
<div class="tab-container">
<div class="sign-in-container result-tab"></div>
<div class="tellafriend-container result-tab email_job_content"></div>
</div>
</div>
</br></div>
<div class="row result" data-jk="e4ae3d5a0b7c9106" id="pj_e4ae3d5a0b7c9106">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/pagead/clk?mo=r&amp;ad=-6NYlbfkN0AdR7ZNjpXdE0tJoOwNQ4mIndKkLeYnvhH58wIOqFz6r_GeZKW98tMIJ9er4AM9LIm08Bwn8mLf6A7s95Q8-zZ8Jcab5Ud9hlr4cYx7sWRyWku2s7S8fG-T84oUS8QRpMTeRIsA2SoQbnOEDNjiBHlHfv8CFbivuG1xQvw5xHVfl_zj8mMph6g6kVkqTTr4oMg1zR8xMIIHvpf1aWXIORCXphzmyOAe6JU2554pV8-AM5EERb5X6A06BSeEXY-9OToBpfTBwxH7zFpKaMmkSt1QuBUFDbD9kxPSdJOLDHhUdSdMxsF0HNiNqtjqsMq2JIcZGxYgXJz5SFynfR--c4XZUjjBAbm-efWyyJmfmGJfdMX6KMRQEYn09WEtoEzWLMtGjg3Q7UPWTG-57wfc54qupXbsiUJFa3m2UAl4zY-5J2K-Qy7NJEXVsqG1PHn8ZqQ=&amp;p=2&amp;sk=&amp;fvj=0" id="sja2" onclick="setRefineByCookie(['salest']); sjoc('sja2',0); convCtr('SJ', pingUrlsForGA)" onmousedown="sjomd('sja2'); clk('sja2');" rel="nofollow" target="_blank" title="People Analytics &amp; Research Data Scientist">People Analytics &amp; Research <b>Data</b> <b>Scientist</b></a>
<br>
<div class="sjcl">
<span class="company">
<a class="turnstileLink" data-tn-element="companyName" href="/cmp/Blackrock-Inc." onmousedown="this.href = appendParamsOnce(this.href, 'from=SERP&amp;campaignid=serp-linkcompanyname&amp;fromjk=e4ae3d5a0b7c9106&amp;jcid=2525164414ed9ff4')" target="_blank">
        BlackRock</a></span>

 - <a class="ratingsLabel" data-tn-element="reviewStars" data-tn-variant="cmplinktst2" href="/cmp/Blackrock-Inc./reviews" onmousedown="this.href = appendParamsOnce(this.href, '?campaignid=cmplinktst2&amp;from=SERP&amp;jt=People+Analytics+%26+Research+Data+Scientist&amp;fromjk=e4ae3d5a0b7c9106&amp;jcid=2525164414ed9ff4');" target="_blank" title="Blackrock reviews">
<span class="ratings" style="height: 11px; line-height: 11px; background-image: url(/images/cmp/star_2_sm@2x.png); background-size: 12px 22px;width: 60px;"><span class="rating" style="height: 11px; line-height: 11px; background-image: url(/images/cmp/star_2_sm@2x.png); background-size: 12px 22px;background-position: 0 11px; width: 44.4px;"><!-- --></span></span><span class="slNoUnderline">173 reviews</span></a>
 - <span class="location">New York, NY 10001</span>
</div>
<table border="0" cellpadding="0" cellspacing="0"><tr><td class="snip">
<span class="summary">We are looking for a <b>data</b> <b>scientist</b> with advanced skills in mathematics, technology and <b>data</b> mining to help build algorithms that leverage large quantities of...</span>
</td></tr></table>
<div class="sjCapt">
<div class="result-link-bar-container">
<div class="result-link-bar"><span class=" jasx_serpsjlabel_poststGray ">Sponsored</span> - <span class="tt_set" id="tt_set_11"><span class="savelink2" id="savelink2_e4ae3d5a0b7c9106"><a class="sl resultLink save-job-link" href="#" id="sj_e4ae3d5a0b7c9106" onclick="changeJobState('e4ae3d5a0b7c9106', 'save', 'linkbar', true);return false;" title="Save this job to my.indeed">save job</a></span></span><div class="edit_note_content" id="editsaved2_e4ae3d5a0b7c9106" style="display:none;"></div><script>window['sj_result_e4ae3d5a0b7c9106'] = {"showSource": false, "source": "BlackRock", "loggedIn": false, "showMyJobsLinks": true,"undoAction": "unsave","jobKey": "e4ae3d5a0b7c9106", "myIndeedAvailable": true, "tellAFriendEnabled": false, "showMoreActionsLink": false, "resultNumber": 11, "jobStateChangedToSaved": false, "searchState": "q=data scientist $20,000&amp;l=New+York&amp;start=10", "basicPermaLink": "http://www.indeed.com", "saveJobFailed": false, "removeJobFailed": false, "requestPending": false, "notesEnabled": false, "currentPage" : "serp", "sponsored" : true,"showSponsor" : true,"reportJobButtonEnabled": false, "showMyJobsHired": false, "showSaveForSponsored": true, "showJobAge": true};</script></div></div>
<div class="tab-container">
<div class="sign-in-container result-tab"></div>
<div class="tellafriend-container result-tab email_job_content"></div>
</div>
</div>
</br></div>
<div class="row sjlast result" data-jk="4b798fee48fc1d12" id="pj_4b798fee48fc1d12">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/pagead/clk?mo=r&amp;ad=-6NYlbfkN0AEAtd83Zmm1yN2JRgBxZApFjJr8fA-y45IQxAqYqjWf_UyntIyUipk_dfORTE7zYgBazzexrTrTzLJMOfC8b6zH0ZjB5aWiOl75tm9oaJ9PMNYbSmIhHqLjK0jC3XpTeAFwxBgovVycklSBZhMts1ejD4qNkR6RdCNUlv9zevA69PCBbDVULUqScwX-bVMbg53VK0t7_1-U7otSG8PawgaOt7fpW976PQBX6yt2ehc22HtS6GaT74q1YpSpnuJ4SMsbDeYUw1Azm-ukgUIYDvqGGIPFKHyhc7Yt0VdCShTHKPWxqn9c4WcZhBD4V94lZp62LGpDmcPXgZjc4W6rNYDyS8AEv7MruV6w12hRwmHGdriyZc3TI2li-C_RzZAWd_DxohQEDgXqjH9KTSbzckwZp3QQQVngohI4tsVFjxY0Y25mKGoVkuqWd1xJE7zc2TSEzhlOkd8ch9pAtbZNvbn5gFU_CDY0TdHLme3_5iuX984LlVfLK6ZqX5AZXXtEbqQ7kjj9lx2CNLSF6MoWPPUy7tiTKo5BW4=&amp;p=3&amp;sk=&amp;fvj=0" id="sja3" onclick="setRefineByCookie(['salest']); sjoc('sja3',0); convCtr('SJ', pingUrlsForGA)" onmousedown="sjomd('sja3'); clk('sja3');" rel="nofollow" target="_blank" title="Quantitative Analyst III - Model Risk Execution">Quantitative Analyst III - Model Risk Execution</a>
<br>
<div class="sjcl">
<span class="company">
<a class="turnstileLink" data-tn-element="companyName" href="/cmp/Td-Bank" onmousedown="this.href = appendParamsOnce(this.href, 'from=SERP&amp;campaignid=serp-linkcompanyname&amp;fromjk=4b798fee48fc1d12&amp;jcid=d7114f1cac8d0711')" target="_blank">
        TD Bank</a></span>

 - <a class="ratingsLabel" data-tn-element="reviewStars" data-tn-variant="cmplinktst2" href="/cmp/Td-Bank/reviews" onmousedown="this.href = appendParamsOnce(this.href, '?campaignid=cmplinktst2&amp;from=SERP&amp;jt=Quantitative+Analyst+III+-+Model+Risk+Execution&amp;fromjk=4b798fee48fc1d12&amp;jcid=d7114f1cac8d0711');" target="_blank" title="Td Bank reviews">
<span class="ratings" style="height: 11px; line-height: 11px; background-image: url(/images/cmp/star_2_sm@2x.png); background-size: 12px 22px;width: 60px;"><span class="rating" style="height: 11px; line-height: 11px; background-image: url(/images/cmp/star_2_sm@2x.png); background-size: 12px 22px;background-position: 0 11px; width: 43.8px;"><!-- --></span></span><span class="slNoUnderline">2,409 reviews</span></a>
 - <span class="location">New York, NY</span>
</div>
<table border="0" cellpadding="0" cellspacing="0"><tr><td class="snip">
<span class="summary">The Quantitative Analyst provides model validation and advance qualitative and quantitative analysis for advanced qualitative or quantitative models to meet</span>
</td></tr></table>
<div class="sjCapt">
<div class="result-link-bar-container">
<div class="result-link-bar"><span class=" jasx_serpsjlabel_poststGray ">Sponsored</span> - <span class="tt_set" id="tt_set_12"><span class="savelink2" id="savelink2_4b798fee48fc1d12"><a class="sl resultLink save-job-link" href="#" id="sj_4b798fee48fc1d12" onclick="changeJobState('4b798fee48fc1d12', 'save', 'linkbar', true);return false;" title="Save this job to my.indeed">save job</a></span></span><div class="edit_note_content" id="editsaved2_4b798fee48fc1d12" style="display:none;"></div><script>window['sj_result_4b798fee48fc1d12'] = {"showSource": false, "source": "TD Bank", "loggedIn": false, "showMyJobsLinks": true,"undoAction": "unsave","jobKey": "4b798fee48fc1d12", "myIndeedAvailable": true, "tellAFriendEnabled": false, "showMoreActionsLink": false, "resultNumber": 12, "jobStateChangedToSaved": false, "searchState": "q=data scientist $20,000&amp;l=New+York&amp;start=10", "basicPermaLink": "http://www.indeed.com", "saveJobFailed": false, "removeJobFailed": false, "requestPending": false, "notesEnabled": false, "currentPage" : "serp", "sponsored" : true,"showSponsor" : true,"reportJobButtonEnabled": false, "showMyJobsHired": false, "showSaveForSponsored": true, "showJobAge": true};</script></div></div>
<div class="tab-container">
<div class="sign-in-container result-tab"></div>
<div class="tellafriend-container result-tab email_job_content"></div>
</div>
</div>
</br></div>
</div>
<div class=" row result" data-jk="bd9e6d6b8027d875" data-tn-component="organicJob" id="p_bd9e6d6b8027d875" itemscope="" itemtype="http://schema.org/JobPosting">
<h2 class="jobtitle" id="jl_bd9e6d6b8027d875">
<a class="turnstileLink" data-tn-element="jobTitle" href="/rc/clk?jk=bd9e6d6b8027d875&amp;fccid=1639254ea84748b5" itemprop="title" onclick="setRefineByCookie(['salest']); return rclk(this,jobmap[0],true,0);" onmousedown="return rclk(this,jobmap[0],0);" rel="nofollow" target="_blank" title="Data Scientist, Analytics"><b>Data</b> <b>Scientist</b>, Analytics</a>
</h2>
<span class="company" itemprop="hiringOrganization" itemtype="http://schema.org/Organization">
<span itemprop="name">
<a href="/cmp/Facebook" onmousedown="this.href = appendParamsOnce(this.href, 'from=SERP&amp;campaignid=serp-linkcompanyname&amp;fromjk=bd9e6d6b8027d875&amp;jcid=1639254ea84748b5')" target="_blank">
        Facebook</a></span>
</span>

 - <a class="ratingsLabel" data-tn-element="reviewStars" data-tn-variant="cmplinktst2" href="/cmp/Facebook/reviews" onmousedown="this.href = appendParamsOnce(this.href, '?campaignid=cmplinktst2&amp;from=SERP&amp;jt=Data+Scientist%2C+Analytics&amp;fromjk=bd9e6d6b8027d875&amp;jcid=1639254ea84748b5');" target="_blank" title="Facebook reviews">
<span class="ratings" style="height: 11px; line-height: 11px; background-image: url(/images/cmp/star_2_sm@2x.png); background-size: 12px 22px;width: 60px;"><span class="rating" style="height: 11px; line-height: 11px; background-image: url(/images/cmp/star_2_sm@2x.png); background-size: 12px 22px;background-position: 0 11px; width: 52.199997px;"><!-- --></span></span><span class="slNoUnderline">163 reviews</span></a>
 - <span itemprop="jobLocation" itemscope="" itemtype="http://schema.org/Place"><span class="location" itemprop="address" itemscope="" itemtype="http://schema.org/Postaladdress"><span itemprop="addressLocality">New York, NY</span></span></span>
<table border="0" cellpadding="0" cellspacing="0">
<tr>
<td class="snip">
<div>
<span class="summary" itemprop="description">
The <b>Data</b> <b>Scientist</b> Analytics role has work across the following four areas:. Building key <b>data</b> sets to empower operational and exploratory analysis....</span>
</div>
<div class="result-link-bar-container">
<div class="result-link-bar"><span class="date">3 days ago</span> <span class="tt_set" id="tt_set_0">  -  <span class="savelink2" id="savelink2_bd9e6d6b8027d875"><a class="sl resultLink save-job-link" href="#" id="sj_bd9e6d6b8027d875" onclick="changeJobState('bd9e6d6b8027d875', 'save', 'linkbar', false);return false;" title="Save this job to my.indeed">save job</a></span> - <a class="sl resultLink more-link " href="#" id="tog_0" onclick="toggleMoreLinks('bd9e6d6b8027d875'); return false;">more...</a></span><div class="edit_note_content" id="editsaved2_bd9e6d6b8027d875" style="display:none;"></div><script>window['result_bd9e6d6b8027d875'] = {"showSource": false, "source": "Facebook", "loggedIn": false, "showMyJobsLinks": true,"undoAction": "unsave","relativeJobAge": "3 days ago","jobKey": "bd9e6d6b8027d875", "myIndeedAvailable": true, "tellAFriendEnabled": false, "showMoreActionsLink": true, "resultNumber": 0, "jobStateChangedToSaved": false, "searchState": "q=data scientist $20,000&amp;l=New+York&amp;start=10", "basicPermaLink": "http://www.indeed.com", "saveJobFailed": false, "removeJobFailed": false, "requestPending": false, "notesEnabled": true, "currentPage" : "serp", "sponsored" : false,"reportJobButtonEnabled": false, "showMyJobsHired": false, "showSaveForSponsored": false, "showJobAge": true};</script></div></div>
<div class="tab-container">
<div class="more-links-container result-tab" id="tt_display_0" style="display:none;"><a class="close-link closeLink" href="#" onclick="toggleMoreLinks('bd9e6d6b8027d875'); return false;" title="Close"></a><div class="more_actions" id="more_0"><ul><li><span class="mat">View all <a href="/q-Facebook-l-New-York,-NY-jobs.html" rel="nofollow">Facebook jobs in New York, NY</a> - <a href="/l-New-York,-NY-jobs.html">New York jobs</a></span></li><li><span class="mat">Salary Search: <a href="/salaries/Data-Scientist-Salaries,-New-York-NY" onmousedown="this.href = appendParamsOnce(this.href, '?campaignid=serp-more&amp;fromjk=bd9e6d6b8027d875&amp;from=serp-more');">Data Scientist salaries in New York, NY</a></span></li><li><span class="mat">Learn more about working at <a href="/cmp/Facebook" onmousedown="this.href = appendParamsOnce(this.href, '?fromjk=bd9e6d6b8027d875&amp;from=serp-more&amp;campaignid=serp-more&amp;jcid=1639254ea84748b5');">Facebook</a></span></li><li><span class="mat"><a href="/cmp/Facebook/faq" onmousedown="this.href = appendParamsOnce(this.href, '?from=serp-more&amp;campaignid=serp-more&amp;fromjk=bd9e6d6b8027d875&amp;jcid=1639254ea84748b5');">Facebook questions about work, benefits, interviews and hiring process:</a><ul><li><a href="/cmp/Facebook/faq/what-is-the-interview-process-like?quid=1anlqk8rmb85v9oq" onmousedown="this.href = appendParamsOnce(this.href, '?from=serp-more&amp;campaignid=serp-more&amp;fromjk=bd9e6d6b8027d875&amp;jcid=1639254ea84748b5');">What is the interview process like?</a></li><li><a href="/cmp/Facebook/faq/what-is-the-work-environment-and-culture-like-at-facebook?quid=1b5ikmpdq1bg1517" onmousedown="this.href = appendParamsOnce(this.href, '?from=serp-more&amp;campaignid=serp-more&amp;fromjk=bd9e6d6b8027d875&amp;jcid=1639254ea84748b5');">What is the work environment and culture like at Facebook?</a></li></ul></span></li><li><span class="mat">Related forums:  - <a href="/forum/cmp/Facebook.html">Facebook</a> - <a href="/forum/loc/New-York-New-York.html">New York, New York</a></span></li></ul></div></div><div class="dya-container result-tab"></div>
<div class="tellafriend-container result-tab email_job_content"></div>
<div class="sign-in-container result-tab"></div>
<div class="notes-container result-tab"></div>
</div>
</td>
</tr>
</table>
</div>
<div class=" row result" data-jk="3c854a3ebee4826b" data-tn-component="organicJob" id="p_3c854a3ebee4826b" itemscope="" itemtype="http://schema.org/JobPosting">
<h2 class="jobtitle" id="jl_3c854a3ebee4826b">
<a class="turnstileLink" data-tn-element="jobTitle" href="/rc/clk?jk=3c854a3ebee4826b&amp;fccid=39407476605079e0" itemprop="title" onclick="setRefineByCookie(['salest']); return rclk(this,jobmap[1],true,1);" onmousedown="return rclk(this,jobmap[1],1);" rel="nofollow" target="_blank" title="Director of Data Science, Analytics">Director of <b>Data</b> Science, Analytics</a>
</h2>
<span class="company" itemprop="hiringOrganization" itemtype="http://schema.org/Organization">
<span itemprop="name">
    Averity</span>
</span>

 - <span itemprop="jobLocation" itemscope="" itemtype="http://schema.org/Place"><span class="location" itemprop="address" itemscope="" itemtype="http://schema.org/Postaladdress"><span itemprop="addressLocality">New York, NY</span></span></span>
<table border="0" cellpadding="0" cellspacing="0">
<tr>
<td class="snip">
<nobr>$175,000 - $250,000 a year</nobr>
<div>
<span class="summary" itemprop="description">

In [80]:
import pandas as pd


do_datascience = pd.DataFrame (columns=['comapany', 'job', 'location', 'salary'])

In [81]:
row_results = soup.find_all('div', {'data-tn-element':'jobtitle turnstileLink'})

In [98]:
for entry in row_results:
    # grab the company
    comapany =  entry.find('span', {'class':'company'}).text
    print company
    # grab the job 
    job = entry.find('h2', attrs={'class':'jobtitle'})#.renderContents()
    print job.text
    # grab the location
    location =  entry.find('span', {'class':'location'}).find('i').text
    print location
    # grab the salary
#     salary =  entry.find('span', {'class':'rest-row-name-text'}).text
    # try to find the number of bookings
    try:
        temp = entry.find('div', {'class':'booking'}).text
        match = re.search(r'\d+', temp)
        if match:
            bookings = match.group()
    except:
        bookings = 'NA'
    do_datascience.loc[len(do_datascience)]=[name, location, price, bookings]

In [99]:
# job = entry.find('h2', attrs={'class':'jobtitle'})#.renderContents()
# print job.text
for entry in soup.find_all('h2', attrs={'class':'jobtitle'}):
    print entry.text
# 'data-tn-element

Data Scientist, Analytics


Director of Data Science, Analytics


Analytics - Ads Team


Accenture Analytics - Data Science Manager


Machine Learning Engineer


Data Analytics Engineer


Sr. Data Scientist, Analytics


Machine Learning Engineer - NY


Scientist - Business Process Modeling and Simulation


Research Analyst, Grid Edge Microgrids; Greentech Media (GTM...

In [84]:
# 1st approach
for entry in soup.find_all('div', {'class':'result'}):
    title =entry.find('a',attrs= {"class":"turnstileLink"})
    location = entry.find('span',attrs= {"class":"location"})
    company = entry.find('span', attrs = {"class":"company"})
    try:
        salary = entry.find('nobr')
    except:
        salary = 'NA'
        
    print title.text
    print location.text
    print company.text
    print salary

Senior Data Scientist
New York, NY

    NIT Finance
None
People Analytics & Research Data Scientist
New York, NY 10001


        BlackRock
None
Quantitative Analyst III - Model Risk Execution
New York, NY


        TD Bank
None
Data Scientist, Analytics
New York, NY



        Facebook

None
Director of Data Science, Analytics
New York, NY


    Averity

<nobr>$175,000 - $250,000 a year</nobr>
Analytics - Ads Team
New York, NY



        Foursquare

None
Accenture Analytics - Data Science Manager
New York, NY 10011 (Chelsea area)



        Accenture

None
Machine Learning Engineer
New York, NY


    AdTheorent

None
Data Analytics Engineer
New York, NY


    Fractal Industries

None
Sr. Data Scientist, Analytics
New York, NY



        Memorial Sloan Kettering

None
Machine Learning Engineer - NY
New York, NY 10032 (Washington Heights area)



        Morgan Stanley

None
Scientist - Business Process Modeling and Simulation
New York, NY



        AIG

None
Research Analyst, Grid Edge Microgrids; Greentech Media (GTM...
New York, NY 10018 (Clinton area)



        Wood Mackenzie

None
Applied Machine Learning Scientist/Engineer - Relevance & Di...
New York, NY


        Bloomberg
None
Data Scientist - Big Data & Analytics
New York, NY 10154


        KPMG
None

In [137]:
# the crawler, changes the url and the city and then appends it to the list for further quering (RA)
url_template = "http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start={:d}".format(1)
max_results_per_city = 100 
results = []
for city in set(['New+York', 'Chicago', 'San+Francisco', 'Austin', 'Seattle', 
    'Los+Angeles', 'Philadelphia', 'Atlanta', 'Dallas', 'Pittsburgh', 
    'Portland', 'Phoenix', 'Denver', 'Houston', 'Miami']):
    for start in range(0, max_results_per_city, 10):
        url_template = "http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l={:s}&start={:d}".format(city, start)
        print url_template

http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Houston&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Houston&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Houston&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Houston&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Houston&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Houston&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Houston&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Houston&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Houston&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Houston&start=90
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Phoenix&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Phoenix&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Phoenix&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Phoenix&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Phoenix&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Phoenix&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Phoenix&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Phoenix&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Phoenix&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Phoenix&start=90
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Chicago&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Chicago&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Chicago&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Chicago&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Chicago&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Chicago&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Chicago&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Chicago&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Chicago&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Chicago&start=90
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=San+Francisco&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=San+Francisco&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=San+Francisco&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=San+Francisco&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=San+Francisco&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=San+Francisco&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=San+Francisco&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=San+Francisco&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=San+Francisco&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=San+Francisco&start=90
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start=90
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Dallas&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Dallas&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Dallas&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Dallas&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Dallas&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Dallas&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Dallas&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Dallas&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Dallas&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Dallas&start=90
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Philadelphia&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Philadelphia&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Philadelphia&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Philadelphia&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Philadelphia&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Philadelphia&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Philadelphia&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Philadelphia&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Philadelphia&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Philadelphia&start=90
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Denver&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Denver&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Denver&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Denver&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Denver&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Denver&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Denver&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Denver&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Denver&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Denver&start=90
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Los+Angeles&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Los+Angeles&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Los+Angeles&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Los+Angeles&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Los+Angeles&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Los+Angeles&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Los+Angeles&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Los+Angeles&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Los+Angeles&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Los+Angeles&start=90
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Pittsburgh&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Pittsburgh&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Pittsburgh&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Pittsburgh&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Pittsburgh&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Pittsburgh&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Pittsburgh&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Pittsburgh&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Pittsburgh&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Pittsburgh&start=90
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Miami&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Miami&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Miami&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Miami&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Miami&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Miami&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Miami&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Miami&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Miami&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Miami&start=90
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Atlanta&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Atlanta&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Atlanta&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Atlanta&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Atlanta&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Atlanta&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Atlanta&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Atlanta&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Atlanta&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Atlanta&start=90
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Seattle&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Seattle&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Seattle&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Seattle&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Seattle&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Seattle&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Seattle&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Seattle&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Seattle&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Seattle&start=90
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Austin&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Austin&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Austin&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Austin&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Austin&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Austin&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Austin&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Austin&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Austin&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Austin&start=90
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Portland&start=0
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Portland&start=10
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Portland&start=20
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Portland&start=30
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Portland&start=40
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Portland&start=50
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Portland&start=60
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Portland&start=70
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Portland&start=80
http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=Portland&start=90

While this has some more verbose elements removed, we can see that there is some structure to the above:
- The salary is available in a nobr element inside of a td element with class='snip.
- The title of a job is in a link with class set to jobtitle and a data-tn-element="jobTitle.
- The location is set in a span with class='location'.
- The company is set in a span with class='company'.

## Write 4 functions to extract each item: location, company, job, and salary.¶
Example
```python
def extract_location_from_result(result):
    return result.find ...
```

##### - Make sure these functions are robust and can handle cases where the data/field may not be available.
>- Remember to check if a field is empty or None for attempting to call methods on it
>- Remember to use try/except if you anticipate errors.

- **Test** the functions on the results above and simple examples

In [227]:
def scrap():
    for row in soup.find_all('td', {'id':'resultsCol'}):
        classes= row.find_all('div', {'class':'result'}) 
        for entry in classes:
            title =entry.find('a',attrs= {"class":"turnstileLink"}).get_text()
            location = entry.find('span',attrs= {"class":"location"}).get_text()
            try:
                company = entry.find('span', attrs = {"class":"company"}).get_text()
            except:
                company = 'NA'
            try:
                salary = entry.find('nobr').get_text()
            except:
                salary = 'NA'
            data_scientist.loc[len(data_scientist)]=[title.strip(), location.strip(), company.strip(), salary]

Now, to scale up our scraping, we need to accumulate more results. We can do this by examining the URL above.
- "http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start=10"

There are two query parameters here we can alter to collect more results, the l=New+York and the start=10. The first controls the location of the results (so we can try a different city). The second controls where in the results to start and gives 10 results (thus, we can keep incrementing by 10 to go further in the list).
##### Complete the following code to collect results from multiple cities and starting points.
- Enter your city below to add it to the search
- Remember to convert your salary to U.S. Dollars to match the other cities if the currency is different

In [228]:
YOUR_CITY = 'Washington DC'

In [241]:
url_template = "http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l={}&start={}"
max_results_per_city = 200 # Set this to a high-value (5000) to generate more results. 
# Crawling more results, will also take much longer. First test your code on a small number of results and then expand.

results = []

for city in set(['New+York', 'Chicago', 'San+Francisco', 'Austin', 'Seattle', 
    'Los+Angeles', 'Philadelphia', 'Atlanta', 'Dallas', 'Pittsburgh', 
    'Portland', 'Phoenix', 'Denver', 'Houston', 'Miami', YOUR_CITY]):
    for start in range(0, max_results_per_city, 10):
        
        # Grab the results from the request (as above)
        for start in range(0, max_results_per_city, 10):
            url_template = "http://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l={:s}&start={:d}".format(city, start)
            results.append(url_template)
        
        
        # Append to the full set of results
        pass

In [ ]:
print city + " Done"
print datetime.datetime.now()

In [248]:
counter = 0
for i in results:
    r = requests.get(i)
    soup = BeautifulSoup(r.text,"html.parser")
    scrap()
    counter += 1
    print counter

1
2
3
4
5
6
7
8

KeyboardInterrupt:

In [249]:
data_scientist

,title,company,location,salary
0,Research Associate II – Immunotherapy,Bellicum Pharmaceuticals,"Houston, TX 77030",NA
1,Quality Assurance Specialist - Transfusion,MD Anderson Cancer Center,"Houston, TX",NA
2,BI/Data Scientist,Robert Half Technology,"Houston, TX 77019",NA
3,Orbital Debris Scientist - ERC,"ERC, Inc.","Johnson, TX",NA
4,Data Scientist,Predictive Science,United States,NA
5,Project Associate,alliantgroup,"Houston, TX",NA
6,Property Accounting / Management Specialist,BOEING,"Houston, TX",NA
7,Data Scientist,PREDICTif Solutions,"Houston, TX 77024",NA
8,Medical Technologist - West Tower (3p - 11:30p),Texas Children's Hospital,"Houston, TX",NA
9,UX Designer,Modis,"Spring, TX 77380",NA
10,Senior ETL Lead/Developer Hadoop Ecosystem,"Karmel Software Solutions Inc.,","Houston, TX 77005",NA
11,Medical Technologist - Blood Bank / General La...,Texas Children's Hospital,"Houston, TX",NA
12,Medical Technologist - Generalist - West Campu...,Texas Children's Hospital,"Houston, TX",NA
13,Research Associate II – Immunotherapy,Bellicum Pharmaceuticals,"Houston, TX 77030",NA
14,Quality Assurance Specialist - Transfusion,MD Anderson Cancer Center,"Houston, TX",NA
15,BI/Data Scientist,Robert Half Technology,"Houston, TX 77019",NA
16,Orbital Debris Scientist - ERC,"ERC, Inc.","Johnson, TX",NA
17,Data Scientist,Predictive Science,United States,NA
18,Project Associate,alliantgroup,"Houston, TX",NA
19,Property Accounting / Management Specialist,BOEING,"Houston, TX",NA
20,Data Scientist,PREDICTif Solutions,"Houston, TX 77024",NA
21,Medical Technologist - West Tower (3p - 11:30p),Texas Children's Hospital,"Houston, TX",NA
22,UX Designer,Modis,"Spring, TX 77380",NA
23,Senior ETL Lead/Developer Hadoop Ecosystem,"Karmel Software Solutions Inc.,","Houston, TX 77005",NA
24,Medical Technologist - Blood Bank / General La...,Texas Children's Hospital,"Houston, TX",NA
25,Medical Technologist - Generalist - West Campu...,Texas Children's Hospital,"Houston, TX",NA
26,Research Associate II – Immunotherapy,Bellicum Pharmaceuticals,"Houston, TX 77030",NA
27,Quality Assurance Specialist - Transfusion,MD Anderson Cancer Center,"Houston, TX",NA
28,BI/Data Scientist,Robert Half Technology,"Houston, TX 77019",NA
29,Orbital Debris Scientist - ERC,"ERC, Inc.","Johnson, TX",NA
...,...,...,...,...
186081,Research Scientist - HPC Application Specialist,"Houston, TX",University of Houston,NA
186082,"Principal Engineer I, RD&E","Sugar Land, TX","NALCO Champion, An Ecolab Company",NA
186083,Data Scientist,United States,Predictive Science,NA
186084,"Senior Scientist (Houston, TX)","Houston, TX",KBRWyle,NA
186085,Quality Assurance Specialist - Transfusion,"Houston, TX",MD Anderson Cancer Center,NA
186086,Orbital Debris Scientist - ERC,"Johnson, TX","ERC, Inc.",NA
186087,Project Associate,"Houston, TX",alliantgroup,NA
186088,Quantitative Research Scientist - Options Stra...,"Houston, TX",Quantlab Financial,NA
186089,Certifying Scientist / LC-MS Chemist,"Houston, TX",Nationwide Laboratory Partners LLC,NA
186090,Systems Engineer - Linux,"Houston, TX",Cray,NA
186091,EPA Scientist,"Sugar Land, TX 77478",AmerisourceBergen,NA
186092,Feasibility Research Analyst II - Novella Clin...,"Houston, TX",Novella Clinical,NA
186093,Sr Research Technician in Biorepository Core,"Houston, TX",Texas Heart Institute,NA
186094,Senior Software Developer / Big Data,"Houston, TX",Brunel Energy,NA
186095,"Specialist - Operations Performance, Energy In...","Houston, TX",McKinsey & Company,NA
186096,Orbital Debris Scientist,"Houston, TX",Jacobs,NA
186097,Product Manager,"Houston, TX",Tachyus,NA
186098,Data Scientist,United States,Predictive Science,NA
186099,"Senior Scientist (Houston, TX)","Houston, TX",KBRWyle,NA
186100,Data Scientist,United States,Predictive Science,NA
186101,Orbital Debris Scientist - ERC,"Johnson, TX","ERC, Inc.",NA
186102,Project Associate,"Houston, TX",alliantgroup,NA
186103,Sr Staff Analytics Engineer,"Houston, TX 77002 (Downtown area)",General Electric,NA
186104,Postdoctoral Researcher: Mineralogy and Petrol...,"Houston, TX 77058 (Pasadena area)",Universities Space Research Association,NA
186105,"Specialist - Operations Performance, Energy In...","Houston, TX",McKinsey & Company,NA
186106,Program Manager- Research,"Houston, TX",UT Health Science Center at Houston,NA
186107,Air Monitoring Specialist -PM 2.5,"Houston, TX",Alion Science and Technology,NA
186108,"Senior Analyst, Technical Accounting and Resea...","Houston, TX",Targa Resources,NA
186109,"Accenture Insights Platform Product Manager, S...","Houston, TX",Accenture,NA
186110,"Medical Science Liaison (MSL), Hematology - My...","Houston, TX 77002 (Downtown area)",Celgene Corporation,NA

In [250]:
data_scientist.to_csv("~/Desktop/data_scientist5.0.csv", encoding='utf-8')

In [251]:
data_scientist1 = data_scientist

In [252]:
data_scientist1.shape

(186111, 4)

In [266]:
def eda(dataframe):
    print "missing values \n", dataframe.isnull().sum()
    print "dataframe types \n", dataframe.dtypes
    print "dataframe shape \n", dataframe.shape
    print "dataframe describe \n", dataframe.describe()
    print "found values \n", dataframe.notnull().sum()
    print "duplicates", dataframe.duplicated().sum()
#     print "fill in missing values", dataframe.continent.fillna(value='NA', inplace=True)
    # drop missing values
#     print " drop a row", dataframe.drinks.dropna()             # drop a row if ANY values are missing
#     print "drop a row only if ALL values are missing", dataframe.drinks.dropna(how='all') # drop a row only if ALL values are missing
    for item in dataframe:
        print item
        print data_scientist1[item].nunique()

eda(data_scientist1)

 missing values
title       0
company     0
location    0
salary      0
dtype: int64
dataframe types
title       object
company     object
location    object
salary      object
dtype: object
dataframe shape
(186111, 4)
dataframe describe
                 title        company       location  salary
count           186111         186111         186111  186111
unique            2079            627           1469     161
top     Data Scientist  United States  United States      NA
freq             22430          12582          10726  180134
found values
title       186111
company     186111
location    186111
salary      186111
dtype: int64
duplicates 183192
title
2079
company
627
location
1469
salary
161

In [258]:
data_scientist1.salary.notnull().sum()

186111

In [259]:
data_scientist1.duplicated().sum()

183192

In [2]:
import pandas as pd
data_scientist1_0 = pd.read_csv('~/Desktop/data_scientist1.0.csv')  # joint

In [3]:
data_scientist2_0 = pd.read_csv('~/Desktop/data_scientist2.0.csv')

In [4]:
data_scientist3_0 = pd.read_csv('~/Desktop/data_scientist3.0.csv')

In [5]:
data_scientist4_0 = pd.read_csv('~/Desktop/data_scientist4.0.csv')

In [6]:
data_scientist5_0 = pd.read_csv('~/Desktop/data_scientist5.0.csv')

In [8]:
# Joining all CSV that I scrapped
Data_ScientistFinal = pd.concat([data_scientist1_0, data_scientist2_0, data_scientist3_0, data_scientist4_0, data_scientist5_0])

In [9]:
Data_ScientistFinal.head()

,Unnamed: 0,title,company,location,salary
0,0,Research Associate II – Immunotherapy,Bellicum Pharmaceuticals,"Houston, TX 77030",NaN
1,1,Quality Assurance Specialist - Transfusion,MD Anderson Cancer Center,"Houston, TX",NaN
2,2,BI/Data Scientist,Robert Half Technology,"Houston, TX 77019",NaN
3,3,Orbital Debris Scientist - ERC,"ERC, Inc.","Johnson, TX",NaN
4,4,Data Scientist,Predictive Science,United States,NaN

In [ ]:
Data_ScientistFinal.drop('Unnamed: 0', axis=1) # axis=0 for rows, 1 for columns
Data_ScientistFinal.drop_duplicates(inplace=True) # drop duplicate rows
Data_ScientistFinal.salary.replace(regex=True, inplace=True, to_replace="\$", value="") # replace $

In [12]:
Data_ScientistFinal.head()

,title,company,location,salary
0,Research Associate II – Immunotherapy,Bellicum Pharmaceuticals,"Houston, TX 77030",NaN
1,Quality Assurance Specialist - Transfusion,MD Anderson Cancer Center,"Houston, TX",NaN
2,BI/Data Scientist,Robert Half Technology,"Houston, TX 77019",NaN
3,Orbital Debris Scientist - ERC,"ERC, Inc.","Johnson, TX",NaN
4,Data Scientist,Predictive Science,United States,NaN

In [268]:
# data_scientist1.groupby('title').salary.agg(['count', 'mean', 'min', 'max'])

DataError: No numeric types to aggregate

In [18]:
only_salaries = Data_ScientistFinal[Data_ScientistFinal.salary.notnull()]
yearly_only = only_salaries[only_salaries.salary.str.contains('year')]

In [21]:
type(yearly_only)

pandas.core.frame.DataFrame

In [24]:
yearly_only.salary.replace(regex=True, inplace=True, to_replace="a year", value="") # replace a year

In [16]:
Data_ScientistFinal.shape
Data_ScientistFinal.describe()

                 title       company          location          salary
count             2919          2919              2918             217
unique            2079           627              1468             160
top     Data Scientist  New York, NY  Magic Leap, Inc.  120,000 a year
freq               127           136                49               6

In [25]:
yearly_only.head()

,title,company,location,salary
56534,Research Analyst-Clearing House,"Chicago, IL",Huxley Banking & Financial Services,"90,000"
56831,Associate Data Scientist,"San Mateo, CA",Harnham,"130,000"
57118,"Senior Data Scientist for Multi-Billion, Top-R...","New York, NY",Averity,"100,000 - 120,000"
57119,"Environmental Analyst, Bureau of Environmental...","Manhattan, NY",DEPT OF HEALTH/MENTAL HYGIENE,"70,286 - 87,295"
57713,Senior Statistician/Data Scientist-PHARMA,"Horsham, PA",Smith Hanley Associates,"120,000"

In [26]:
yearly_only.rename(columns={'company':'location', 'location':'company'}, inplace=True) # changed names of columns

/Users/josephlbrown/anaconda/lib/python2.7/site-packages/pandas/core/frame.py:2834: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)

In [27]:
yearly_only.head()

,title,location,company,salary
56534,Research Analyst-Clearing House,"Chicago, IL",Huxley Banking & Financial Services,"90,000"
56831,Associate Data Scientist,"San Mateo, CA",Harnham,"130,000"
57118,"Senior Data Scientist for Multi-Billion, Top-R...","New York, NY",Averity,"100,000 - 120,000"
57119,"Environmental Analyst, Bureau of Environmental...","Manhattan, NY",DEPT OF HEALTH/MENTAL HYGIENE,"70,286 - 87,295"
57713,Senior Statistician/Data Scientist-PHARMA,"Horsham, PA",Smith Hanley Associates,"120,000"

In [28]:
yearly_only.salary.replace(regex=True, inplace=True, to_replace=",", value="")

In [31]:
yearly_only.head()

,title,location,company,salary
56534,Research Analyst-Clearing House,"Chicago, IL",Huxley Banking & Financial Services,90000
56831,Associate Data Scientist,"San Mateo, CA",Harnham,130000
57118,"Senior Data Scientist for Multi-Billion, Top-R...","New York, NY",Averity,100000 - 120000
57119,"Environmental Analyst, Bureau of Environmental...","Manhattan, NY",DEPT OF HEALTH/MENTAL HYGIENE,70286 - 87295
57713,Senior Statistician/Data Scientist-PHARMA,"Horsham, PA",Smith Hanley Associates,120000

In [32]:
yearly_only.salary.describe()

count         155
unique        112
top       120000
freq            6
Name: salary, dtype: object

In [38]:
print yearly_only.salary.mean

<bound method Series.mean of 56534               90000
56831              130000
57118     100000 - 120000
57119       70286 - 87295
57713              120000
58318     100000 - 109000
59309      90000 - 120000
60411      80000 - 120000
60441       50000 - 80000
60445               43794
60448              105000
60480       40800 - 79100
60487       66400 - 99600
60493               65000
60770               46831
60853               60000
66395              150000
66426       39983 - 55500
66452       45000 - 77000
66459       63696 - 94557
66468       45000 - 55000
66482       49000 - 61000
66484       50000 - 55000
66486       50000 - 61500
66500       30000 - 45000
66516       33000 - 42000
66518     100000 - 130000
66529       39173 - 54944
66531       60000 - 80000
72276       70000 - 90000
                ...
162125             120000
162130    125132 - 161900
162177              58600
162309             120000
162382     70000 - 145000
162491      45000 - 55000
162624              24000
162642      30000 - 32000
168123    125000 - 160000
168124    100000 - 135000
168130    100000 - 135000
168215    100000 - 150000
168322              35000
168363     82326 - 104374
169900    155000 - 165000
174129    110000 - 150000
174132      55579 - 62254
174156      75000 - 90000
174200      40000 - 47000
174206              90000
174245              79000
174364             120000
174369     80000 - 100000
174397     80000 - 120000
180131              45000
180160              47484
180192    160000 - 180000
180199             100000
180231    100000 - 130000
180234    120000 - 165000
Name: salary, dtype: object>

In [41]:
yearly_only['split_salary'] = yearly_only['salary'].str.split('-')

/Users/josephlbrown/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [42]:
yearly_only.head()

,title,location,company,salary,split_salary
56534,Research Analyst-Clearing House,"Chicago, IL",Huxley Banking & Financial Services,90000,[90000 ]
56831,Associate Data Scientist,"San Mateo, CA",Harnham,130000,[130000 ]
57118,"Senior Data Scientist for Multi-Billion, Top-R...","New York, NY",Averity,100000 - 120000,"[100000 , 120000 ]"
57119,"Environmental Analyst, Bureau of Environmental...","Manhattan, NY",DEPT OF HEALTH/MENTAL HYGIENE,70286 - 87295,"[70286 , 87295 ]"
57713,Senior Statistician/Data Scientist-PHARMA,"Horsham, PA",Smith Hanley Associates,120000,[120000 ]

In [48]:
yearly_only['lower'] = yearly_only["split_salary"].str[0]
yearly_only['upper'] = yearly_only["split_salary"].str[1]

/Users/josephlbrown/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/josephlbrown/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [49]:
yearly_only['lower'] = yearly_only.lower.astype(float)
yearly_only['upper'] = yearly_only.upper.astype(float)

/Users/josephlbrown/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/josephlbrown/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [50]:
yearly_only.head()

,title,location,company,salary,split_salary,lower,uppper,upper
56534,Research Analyst-Clearing House,"Chicago, IL",Huxley Banking & Financial Services,90000,[90000 ],90000.0,NaN,NaN
56831,Associate Data Scientist,"San Mateo, CA",Harnham,130000,[130000 ],130000.0,NaN,NaN
57118,"Senior Data Scientist for Multi-Billion, Top-R...","New York, NY",Averity,100000 - 120000,"[100000 , 120000 ]",100000.0,120000,120000.0
57119,"Environmental Analyst, Bureau of Environmental...","Manhattan, NY",DEPT OF HEALTH/MENTAL HYGIENE,70286 - 87295,"[70286 , 87295 ]",70286.0,87295,87295.0
57713,Senior Statistician/Data Scientist-PHARMA,"Horsham, PA",Smith Hanley Associates,120000,[120000 ],120000.0,NaN,NaN

In [51]:
yearly_only['mean'] = yearly_only[['upper', 'lower']].mean(axis=1)

/Users/josephlbrown/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [52]:
yearly_only.head()

,title,location,company,salary,split_salary,lower,uppper,upper,mean
56534,Research Analyst-Clearing House,"Chicago, IL",Huxley Banking & Financial Services,90000,[90000 ],90000.0,NaN,NaN,90000.0
56831,Associate Data Scientist,"San Mateo, CA",Harnham,130000,[130000 ],130000.0,NaN,NaN,130000.0
57118,"Senior Data Scientist for Multi-Billion, Top-R...","New York, NY",Averity,100000 - 120000,"[100000 , 120000 ]",100000.0,120000,120000.0,110000.0
57119,"Environmental Analyst, Bureau of Environmental...","Manhattan, NY",DEPT OF HEALTH/MENTAL HYGIENE,70286 - 87295,"[70286 , 87295 ]",70286.0,87295,87295.0,78790.5
57713,Senior Statistician/Data Scientist-PHARMA,"Horsham, PA",Smith Hanley Associates,120000,[120000 ],120000.0,NaN,NaN,120000.0

In [ ]:
# yearly_only.salary.replace(regex=True, inplace=True, to_replace=",", value="") # removing

In [53]:
yearly_only['split_location'] = yearly_only['location'].str.split(',')

/Users/josephlbrown/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [54]:
yearly_only.head()

,title,location,company,salary,split_salary,lower,uppper,upper,mean,split_location
56534,Research Analyst-Clearing House,"Chicago, IL",Huxley Banking & Financial Services,90000,[90000 ],90000.0,NaN,NaN,90000.0,"[Chicago, IL]"
56831,Associate Data Scientist,"San Mateo, CA",Harnham,130000,[130000 ],130000.0,NaN,NaN,130000.0,"[San Mateo, CA]"
57118,"Senior Data Scientist for Multi-Billion, Top-R...","New York, NY",Averity,100000 - 120000,"[100000 , 120000 ]",100000.0,120000,120000.0,110000.0,"[New York, NY]"
57119,"Environmental Analyst, Bureau of Environmental...","Manhattan, NY",DEPT OF HEALTH/MENTAL HYGIENE,70286 - 87295,"[70286 , 87295 ]",70286.0,87295,87295.0,78790.5,"[Manhattan, NY]"
57713,Senior Statistician/Data Scientist-PHARMA,"Horsham, PA",Smith Hanley Associates,120000,[120000 ],120000.0,NaN,NaN,120000.0,"[Horsham, PA]"

In [58]:
yearly_only['city'] = yearly_only["split_location"].str[0]
yearly_only['state'] = yearly_only["split_location"].str[1]
yearly_only['state'] = yearly_only["state"].str[0:3]

/Users/josephlbrown/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/josephlbrown/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Users/josephlbrown/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [59]:
yearly_only.head(10)

,title,location,company,salary,split_salary,lower,uppper,upper,mean,split_location,city,state
56534,Research Analyst-Clearing House,"Chicago, IL",Huxley Banking & Financial Services,90000,[90000 ],90000.0,NaN,NaN,90000.0,"[Chicago, IL]",Chicago,IL
56831,Associate Data Scientist,"San Mateo, CA",Harnham,130000,[130000 ],130000.0,NaN,NaN,130000.0,"[San Mateo, CA]",San Mateo,CA
57118,"Senior Data Scientist for Multi-Billion, Top-R...","New York, NY",Averity,100000 - 120000,"[100000 , 120000 ]",100000.0,120000,120000.0,110000.0,"[New York, NY]",New York,NY
57119,"Environmental Analyst, Bureau of Environmental...","Manhattan, NY",DEPT OF HEALTH/MENTAL HYGIENE,70286 - 87295,"[70286 , 87295 ]",70286.0,87295,87295.0,78790.5,"[Manhattan, NY]",Manhattan,NY
57713,Senior Statistician/Data Scientist-PHARMA,"Horsham, PA",Smith Hanley Associates,120000,[120000 ],120000.0,NaN,NaN,120000.0,"[Horsham, PA]",Horsham,PA
58318,Research Scientist,"Northridge, CA 91324",Arete Associates,100000 - 109000,"[100000 , 109000 ]",100000.0,109000,109000.0,104500.0,"[Northridge, CA 91324]",Northridge,CA
59309,Statistician - Model Validation,"Atlanta, GA",Smith Hanley Associates,90000 - 120000,"[90000 , 120000 ]",90000.0,120000,120000.0,105000.0,"[Atlanta, GA]",Atlanta,GA
60411,Data Scientist,"Houston, TX",Platinum Solutions,80000 - 120000,"[80000 , 120000 ]",80000.0,120000,120000.0,100000.0,"[Houston, TX]",Houston,TX
60441,Bioinformatics Software Developer,"Houston, TX",Genialis,50000 - 80000,"[50000 , 80000 ]",50000.0,80000,80000.0,65000.0,"[Houston, TX]",Houston,TX
60445,Quality Assurance Analyst (Research),"Houston, TX",Baylor College of Medicine,43794,[43794 ],43794.0,NaN,NaN,43794.0,"[Houston, TX]",Houston,TX

In [61]:
yearly_only['mean'].describe()

count       155.000000
mean      98827.664516
std       46396.490927
min       24000.000000
25%       58050.000000
50%       93350.000000
75%      130000.000000
max      250000.000000
Name: mean, dtype: float64

In [62]:
yearly_only["Median_Compare"] = (yearly_only["mean"] >= yearly_only["mean"].median()).astype(int)

/Users/josephlbrown/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [70]:
yearly_only.head(10)

,title,company,mean,city,state,Median_Compare
56534,Research Analyst-Clearing House,Huxley Banking & Financial Services,90000.0,Chicago,IL,0
56831,Associate Data Scientist,Harnham,130000.0,San Mateo,CA,1
57118,"Senior Data Scientist for Multi-Billion, Top-R...",Averity,110000.0,New York,NY,1
57119,"Environmental Analyst, Bureau of Environmental...",DEPT OF HEALTH/MENTAL HYGIENE,78790.5,Manhattan,NY,0
57713,Senior Statistician/Data Scientist-PHARMA,Smith Hanley Associates,120000.0,Horsham,PA,1
58318,Research Scientist,Arete Associates,104500.0,Northridge,CA,1
59309,Statistician - Model Validation,Smith Hanley Associates,105000.0,Atlanta,GA,1
60411,Data Scientist,Platinum Solutions,100000.0,Houston,TX,1
60441,Bioinformatics Software Developer,Genialis,65000.0,Houston,TX,0
60445,Quality Assurance Analyst (Research),Baylor College of Medicine,43794.0,Houston,TX,0

In [71]:
yearly_only.drop(['salary', 'split_salary', 'uppper', 'split_location', 'location', 'lower', 'upper'], axis=1, inplace=True)

ValueError: labels ['salary' 'split_salary' 'uppper' 'split_location' 'location' 'lower'
 'upper'] not contained in axis

In [72]:
yearly_only.head()

,title,company,mean,city,state,Median_Compare
56534,Research Analyst-Clearing House,Huxley Banking & Financial Services,90000.0,Chicago,IL,0
56831,Associate Data Scientist,Harnham,130000.0,San Mateo,CA,1
57118,"Senior Data Scientist for Multi-Billion, Top-R...",Averity,110000.0,New York,NY,1
57119,"Environmental Analyst, Bureau of Environmental...",DEPT OF HEALTH/MENTAL HYGIENE,78790.5,Manhattan,NY,0
57713,Senior Statistician/Data Scientist-PHARMA,Smith Hanley Associates,120000.0,Horsham,PA,1

In [80]:
yearly_dummy = pd.get_dummies(yearly_final.state)

In [77]:
yearly_final = pd.read_csv('~/Desktop/yearly_final.csv')

In [81]:
yearly_final.head()

,Unnamed: 0,title,company,mean,city,state,Median_Compare
0,56534,Research Analyst-Clearing House,Huxley Banking & Financial Services,90000.0,Chicago,IL,0
1,56831,Associate Data Scientist,Harnham,130000.0,San Mateo,CA,1
2,57118,"Senior Data Scientist for Multi-Billion, Top-R...",Averity,110000.0,New York,NY,1
3,57119,"Environmental Analyst, Bureau of Environmental...",DEPT OF HEALTH/MENTAL HYGIENE,78790.5,Manhattan,NY,0
4,57713,Senior Statistician/Data Scientist-PHARMA,Smith Hanley Associates,120000.0,Horsham,PA,1

In [82]:
yearly_dummy.head()

    AZ   CA   CO   DE   FL   GA   IL   NY   OR   PA   TX   WA
0    0    0    0    0    0    0    1    0    0    0    0    0
1    0    1    0    0    0    0    0    0    0    0    0    0
2    0    0    0    0    0    0    0    1    0    0    0    0
3    0    0    0    0    0    0    0    1    0    0    0    0
4    0    0    0    0    0    0    0    0    0    1    0    0

In [84]:
concat_yearly = pd.concat([yearly_final, yearly_dummy], axis=1)

In [86]:
concat_yearly.head()

,Unnamed: 0,title,company,mean,city,state,Median_Compare,AZ,CA,CO,DE,FL,GA,IL,NY,OR,PA,TX,WA
0,56534,Research Analyst-Clearing House,Huxley Banking & Financial Services,90000.0,Chicago,IL,0,0,0,0,0,0,0,1,0,0,0,0,0
1,56831,Associate Data Scientist,Harnham,130000.0,San Mateo,CA,1,0,1,0,0,0,0,0,0,0,0,0,0
2,57118,"Senior Data Scientist for Multi-Billion, Top-R...",Averity,110000.0,New York,NY,1,0,0,0,0,0,0,0,1,0,0,0,0
3,57119,"Environmental Analyst, Bureau of Environmental...",DEPT OF HEALTH/MENTAL HYGIENE,78790.5,Manhattan,NY,0,0,0,0,0,0,0,0,1,0,0,0,0
4,57713,Senior Statistician/Data Scientist-PHARMA,Smith Hanley Associates,120000.0,Horsham,PA,1,0,0,0,0,0,0,0,0,0,1,0,0
5,58318,Research Scientist,Arete Associates,104500.0,Northridge,CA,1,0,1,0,0,0,0,0,0,0,0,0,0
6,59309,Statistician - Model Validation,Smith Hanley Associates,105000.0,Atlanta,GA,1,0,0,0,0,0,1,0,0,0,0,0,0
7,60411,Data Scientist,Platinum Solutions,100000.0,Houston,TX,1,0,0,0,0,0,0,0,0,0,0,1,0
8,60441,Bioinformatics Software Developer,Genialis,65000.0,Houston,TX,0,0,0,0,0,0,0,0,0,0,0,1,0
9,60445,Quality Assurance Analyst (Research),Baylor College of Medicine,43794.0,Houston,TX,0,0,0,0,0,0,0,0,0,0,0,1,0

#### Use the functions you wrote above to parse out the 4 fields - location, title, company and salary. Create a dataframe from the results with those 4 columns.

### Save your results as a CSV

In [14]:
# Export to csv DONT RUN AGAIN
yearly_only.to_csv("~/Desktop/yearly_final.csv", encoding='utf-8')

In [119]:
import pandas_profiling as pdp

pdp.ProfileReport(yearly_final)

## Predicting salaries using Random Forests + Another Classifier

#### Create a Random Forest model to predict High/Low salary using Sklearn. Start by ONLY using the location as a feature.

In [88]:
concat_yearly.head()

,Unnamed: 0,title,company,mean,city,state,Median_Compare,AZ,CA,CO,DE,FL,GA,IL,NY,OR,PA,TX,WA
0,56534,Research Analyst-Clearing House,Huxley Banking & Financial Services,90000.0,Chicago,IL,0,0,0,0,0,0,0,1,0,0,0,0,0
1,56831,Associate Data Scientist,Harnham,130000.0,San Mateo,CA,1,0,1,0,0,0,0,0,0,0,0,0,0
2,57118,"Senior Data Scientist for Multi-Billion, Top-R...",Averity,110000.0,New York,NY,1,0,0,0,0,0,0,0,1,0,0,0,0
3,57119,"Environmental Analyst, Bureau of Environmental...",DEPT OF HEALTH/MENTAL HYGIENE,78790.5,Manhattan,NY,0,0,0,0,0,0,0,0,1,0,0,0,0
4,57713,Senior Statistician/Data Scientist-PHARMA,Smith Hanley Associates,120000.0,Horsham,PA,1,0,0,0,0,0,0,0,0,0,1,0,0

In [115]:

## YOUR CODE HERE
# RandomForestClassifier(n_estimators=10
                       
# df = concat_yearly                     
                       
# from sklearn.datasets import load_iris
# from sklearn.ensemble import RandomForestClassifier
# import pandas as pd
# import numpy as np

# iris = load_iris()
# df = pd.DataFrame(iris.data, columns=iris.feature_names)
# df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
# df['species'] = pd.Factor(iris.target, iris.target_names)
# df.head()

# train, test = df[df['is_train']==True], df[df['is_train']==False]

# features = df.columns[:4]
# clf = RandomForestClassifier(n_jobs=2)
# y, _ = pd.factorize(train['species'])
# clf.fit(train[features], y)

# preds = iris.target_names[clf.predict(test[features])]
# pd.crosstab(test['species'], preds, rownames=['actual'], colnames=['preds'])     
                       


                       
                       
# rf = RandomForestClassifier(class_weight='balanced')
# s = cross_val_score(rf, X_train_transform, y_train, n_jobs=-1)
# print "{} Score:\t{:0.3} ± {:0.3}".format("Random Forrest", s.mean().round(3), s.std().round(3))

In [107]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn import metrics
import numpy as np

logreg = LogisticRegression(random_state=77)
X = concat_yearly[[' AZ',' CA',' CO',' DE',' FL',' GA',' IL',' NY',' OR',' PA',' TX',' WA']]
y = concat_yearly[['Median_Compare']]

X_train, X_test, Y_train, Y_test = train_test_split(X,y ,test_size=0.33)

logreg.fit(X_train, Y_train)
Y_pred = logreg.predict(X_test)
logreg.score(X,y)

0.67096774193548392

In [113]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import cross_val_score

X = concat_yearly[[' AZ',' CA',' CO',' DE',' FL',' GA',' IL',' NY',' OR',' PA',' TX',' WA']]
y = concat_yearly['Median_Compare']

X_train, X_test, y_train, y_test = train_test_split(X,y ,test_size=0.33)

rf.fit(X_train, y_train)

rf = RandomForestClassifier(class_weight='balanced')
s = cross_val_score(rf, X_train, y_train, n_jobs=-1)
print "{} Score:\t{:0.3} ± {:0.3}".format("Random Forrest", s.mean().round(3), s.std().round(3))

# dt = DecisionTreeClassifier(class_weight='balanced')
# s = cross_val_score(dt, X, y, cv=cv, n_jobs=-1)
# print "{} Score:\t{:0.3} ± {:0.3}".format("Decision Tree", s.mean().round(3), s.std().round(3))

Random Forrest Score:	0.62 ± 0.066

#### Create a few new variables in your dataframe to represent interesting features of a job title.
- For example, create a feature that represents whether 'Senior' is in the title 
- or whether 'Manager' is in the title. 
- Then build a new Random Forest with these features. Do they add any value?

In [118]:
## YOUR CODE HERE

import pandas_profiling as pdp

pdp.ProfileReport(concat_yearly)

In [127]:
import seaborn as sns
# change the layout
# concat_yearly.hist(column='mean', by='Median_Compare', sharex=True, layout=(12, 13))
sns.pairplot(concat_yearly)

In [131]:
import seaborn as sns
sns.set(color_codes=True)
sns.set_palette(sns.color_palette("muted"))

sns.distplot(concat_yearly["Median_Compare"].dropna());